sudo: required
services:
  - docker

before_install:
  - docker build -t "hmada15/reach-dock" -f Dockerfile.dev .

script: 
  - docker run -e CI=true "hmada15/reach-dock" npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_acces_key: $SECRETACCESSKEY
  region: "eu-central-1"
  app: "react-dock"
  env: "Reactdock-env"
  bucket_name: "elasticbeanstalk-eu-central-1-111205789458"
  bucket_path: "react-dock"
  on:
    branch: master
